tasks:
# - name: test muti row
#   cmd: yum_repository
#   param: 
#     config: |
#       username:admin
#       password:123456
#     name: "xxxxx" 
#   tag: "test1"
  
- name:  copy {{project}} /tmp/1.txt
  cmd: copy
  param:
    src: "/tmp/1.txt"
    dst: "/tmp/2.txt"
  tag: "test1"

- name: test shell 1
  cmd: shell
  param:
    data: "ls ~"
  tag: "test1"

- name:  template test
  cmd: template
  param:
    src: "main.j2"
    dst: "/tmp/main.yml"
  tag: "test1"


# - name: Creates {{rootDir}}/logs/{{ serviceName }}  directory
#   cmd: file
#   param:
#     path: "{{rootDir}}/logs/{{ serviceName }}/"
#     state: directory
#     owner: "{{userId}}"
#     group: "{{groupId}}"
#     mode: 0755

# - name: create repo for elastic packages
#   cmd: yum_repository
#   param:
#     name: elk
#     description: Elastic 7.x Repo
#     baseurl:  "https://mirrors.bfsu.edu.cn/elasticstack/yum/elastic-7.x/"
#     gpgcheck: 0

# - name: Creating {{groupId}} user group
#   cmd: group
#   param:
#     name: "{{groupId}}"
  

# - name: Creating {{userId}} user
#   cmd: user
#   param:
#     name: "{{userId}}"
#     group: "{{groupId}}"
#     system: yes
#     shell: "/sbin/nologin"
#     comment: "{{userId}} nologin User"
#     createhome: "no"
#     state: present

# - name: install filebeat
#   cmd: yum
#   param:
#     name: filebeat
#     state: present

# - name: Creates {{rootDir}}/logs/{{ serviceName }}  directory
#   cmd: file
#   param:
#     path: "{{rootDir}}/logs/{{ serviceName }}/"
#     state: directory
#     owner: "{{userId}}"
#     group: "{{groupId}}"
#     mode: 0755

# - name: Creates {{rootDir}}/{{ serviceName }} directory
#   cmd: file
#   param:
#     path: "{{rootDir}}/{{ serviceName }}/"
#     state: directory
#     owner: "{{userId}}"
#     group: "{{groupId}}"
#     mode: 0755

# - name: create filebeat config
#   cmd: template
#   param:
#     src: templates/filebeat.yml
#     dest: "{{rootDir}}/{{ serviceName }}/filebeat.yml"

# - name:  cp {{ serviceName }}  service 
#   cmd: template
#   param:
#     src: "{{ serviceName }}.service"
#     dest: "/usr/lib/systemd/system/{{ serviceName }}.service"


# - name: start filebeat service
#   cmd: service
#   param:
#     name: filebeat
#     state: started
#     enabled: yes